### ISSUE TITLE
Common Pipeline setup

### ISSUE THREAD

**Issue by chris-pateman** [hmcts/hmcts.github.io#105]
### What would you like to change?
page: https://hmcts.github.io/ways-of-working/common-pipeline/common-pipeline.html#common-pipeline

Detail on how to use/setup the pipeline would be good.
For example clone a example repo/files for nodeJs and/or Java

Information on the repo to extend the pipeline https://github.com/hmcts/cnp-jenkins-library

Diagram for end to end process of the pipeline, so we can flow where the failures might be:
https://tools.hmcts.net/confluence/display/PUBH/Jenkins+Pipeline+Flow

**Comment by endakelly** [comment]
Hi Chris, some updates have been made to the page as requested. Check it out and fire in another issue if more updates or clarification is required. https://hmcts.github.io/ways-of-working/common-pipeline/common-pipeline.html#common-pipeline
