### ISSUE TITLE
Jenkins Setup

### ISSUE THREAD

**Issue by chris-pateman** [hmcts/hmcts.github.io#106]
### What would you like to change?
page: https://tools.hmcts.net/confluence/display/PUBH/Jenkins+Pipeline+Flow

would be good to split the Jenkins Setup into a separate page as it is hidden in Team setup.
Could also link this with the Common Pipeline.

A section explaining if you have applications in both CFT and SDS you will need to use regex to exclude it from one or the other and get PlatOps to run the [Org Discovery pipeline](https://build.platform.hmcts.net/job/HMCTS_HMI/computation/console)

**Comment by timja** [comment]
> A section explaining if you have applications in both CFT and SDS you will need to use regex to exclude it from one or the other and get PlatOps to run the Org Discovery pipeline

I think that's very special case in that HMI started building on CFT and migrated to ADO but never removed their config

**Comment by timja** [comment]
This is addressed now
