### ISSUE TITLE
Environments and their detail

### ISSUE THREAD

**Issue by chris-pateman** [hmcts/hmcts.github.io#133]
### What would you like to change?
I would like to see a page that describe what all the environments are and what they are used for with naming conventions for CFT and SDS

### How do you think that would improve the project?
This will give clarity to others on what the use case for environments are for.

**Comment by endakelly** [comment]
@chris-pateman can you review the updates here please and let us know if that resolves the issue? https://hmcts.github.io/ways-of-working/standards/environments.html

**Comment by endakelly** [comment]
Chris confirmed the changes have answered this query
