### ISSUE TITLE
Re: 'Team'

### ISSUE THREAD

**Issue by bugbare-reform** [hmcts/hmcts.github.io#55]
Problem with 'Team' (hmcts.github.io/onboarding/team/)
Not a problem - more a query:

 Is the list of activities ordered from top to bottom? 

A new team who have just gone through onboarding just asked me if they need to setup the github team first (at the bottom of this page) -  I wasn't sure but said that it sounds logical to create a team on github first. 

If it should be done at the start, can it be moved to the top of the page?

**Comment by timja** [comment]
👋 yes it makes sense to move up, doing now

**Comment by timja** [comment]
PR created https://github.com/hmcts/hmcts.github.io/pull/56
